// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Operações de schema (db push / migrate) usam a conexão DIRETA (porta 5432).
    // A pooler de transação (6543) não suporta o que essas operações precisam.
    // O app em runtime usa DATABASE_URL (pooler) via o adapter em src/lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
